const fs = require("fs");
const path = require("path");

const postsPath = path.join(process.cwd(), "posts.json");
const researchedPath = path.join(process.cwd(), "researched_questions.json");

const posts = JSON.parse(fs.readFileSync(postsPath, "utf8"));
const researched = JSON.parse(fs.readFileSync(researchedPath, "utf8"));
const all = [...posts, ...researched];

const TARGET = 26;

function slugify(value) {
  return String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
}

const topicQuestionPools = {
  "software-engineering": [
    ["system-design-tradeoffs", "How do you explain architectural tradeoffs to non-engineers?", "I translate the tradeoff into outcomes the team cares about, such as speed of delivery, reliability, cost, and future flexibility. The goal is not to simplify the engineering into something inaccurate, but to make the decision understandable and reviewable.", "Connect technical choices to business consequences."],
    ["incident-response", "What is your approach during a production incident?", "I first focus on reducing user impact, then I gather enough evidence to identify the failure path, communicate status clearly, and avoid making random changes under pressure. After recovery, I document the cause and prevention steps so the same issue is less likely to repeat.", "Stabilization comes before deep diagnosis."],
    ["estimating-work", "How do you estimate engineering work realistically?", "I break the work into smaller pieces, identify unknowns and dependencies, and separate the likely path from the risky path. Realistic estimates come from exposing uncertainty early instead of hiding it behind one optimistic number.", "Mention dependencies and unknowns."],
    ["backward-compatibility", "When is backward compatibility especially important?", "Backward compatibility matters when existing clients, users, or internal systems depend on behavior that cannot change safely all at once. Preserving compatibility protects trust and gives teams a path to evolve systems without forcing disruption.", "Show that compatibility is a product decision as well as a technical one."],
    ["refactor-vs-rewrite", "How do you decide between refactoring and rewriting?", "I prefer refactoring when the current system still has useful structure and the risk of incremental improvement is lower than a rewrite. I choose a rewrite only when the existing foundation blocks progress so deeply that incremental change becomes more expensive and less safe than replacement.", "Incremental change is usually the default."],
    ["cross-team-dependency", "How do you manage a feature that depends on another team?", "I make the dependency explicit early, align on contracts and timelines, and reduce coupling where possible so progress does not stall completely. Dependency management is strongest when assumptions are written down instead of left informal.", "Emphasize explicit contracts and visibility."],
    ["root-cause-analysis", "What makes a good root cause analysis?", "A good root cause analysis explains not only what failed, but why the system allowed the failure to happen and how similar failures can be prevented. It should improve understanding and action, not assign blame theatrically.", "Focus on prevention, not blame."],
    ["safe-rollouts", "How do you release risky changes safely?", "I reduce risk through smaller deployments, feature flags, monitoring, clear rollback criteria, and staged rollout where possible. Safe releases come from limiting blast radius and keeping observation tight around the change.", "Blast radius is a useful phrase here."],
    ["engineering-ownership", "What does ownership mean in software engineering?", "Ownership means seeing the problem through from unclear request to reliable outcome, including implementation, communication, validation, and follow-up. It is broader than writing code because it includes making sure the result actually works for users and the team.", "Ownership includes follow-through."],
    ["scaling-team-quality", "How do you maintain quality as an engineering team grows?", "I rely on shared standards, code review quality, automation, and clear design decisions so consistency does not depend on one person remembering everything. Growing teams need systems that make good behavior easier.", "Talk about systems, not only individual discipline."],
    ["performance-bottleneck", "How do you identify the real bottleneck in a slow system?", "I measure the user path first, then narrow the dominant cost with logs, metrics, or profiling rather than guessing from intuition. Bottlenecks are often different from where teams first feel the pain, so evidence matters.", "Always anchor on measurement."],
    ["designing-apis", "What makes an internal API easy to work with?", "A good internal API is clear, stable, observable, and named around the domain instead of accidental implementation detail. Teams move faster when APIs reduce ambiguity instead of forcing everyone to rediscover the same behavior separately.", "Use clarity and stability as the main points."],
    ["requirements-changes", "How do you handle changing requirements in the middle of development?", "I reassess scope based on what changed, identify what work remains valid, and update stakeholders on the cost of the new direction. Good handling of changing requirements is mostly about clarity and controlled adjustment, not frustration.", "Show adaptability without sounding passive."],
    ["mentoring-juniors", "How do you help junior engineers improve?", "I try to give guidance that improves their decision-making, not just the code in front of us. That means explaining the why behind changes, creating space for them to reason aloud, and helping them build habits they can reuse independently.", "Teaching the why is stronger than fixing everything yourself."],
    ["engineering-metrics", "Which engineering metrics do you actually trust?", "I trust metrics that connect to user impact or delivery health, such as failure rate, change lead time, and recovery time, but only when teams interpret them with context. Metrics help most when they guide questions rather than become vanity dashboards.", "Avoid sounding metric-blind or metric-obsessed."],
    ["de-risking-project", "How do you de-risk a large project early?", "I identify the assumptions most likely to fail and test those before polishing the easier parts. Projects get safer when the hardest unknowns are surfaced quickly instead of being discovered near launch.", "Unknowns should be tackled before cosmetic progress."],
    ["engineering-principles", "What engineering principles do you rely on most?", "I rely on clarity, correctness, small changes, and evidence-based decisions because those principles scale well across products and teams. Strong principles help when details are messy because they keep judgment consistent.", "Keep the principles practical rather than philosophical."]
  ],
  "javascript": [
    ["prototype-chain", "What is the prototype chain in JavaScript?", "Objects in JavaScript can inherit properties and behavior through a linked prototype chain. When a property is not found on the object itself, the runtime looks up the chain until it either finds the property or reaches the end.", "Tie the explanation to property lookup."],
    ["shallow-vs-deep-copy", "What is the difference between a shallow copy and a deep copy?", "A shallow copy duplicates the top-level container but still shares nested references, while a deep copy duplicates nested structures as well. The difference matters when updating objects because shallow copies can still allow hidden mutation of nested data.", "Nested references are the key detail."],
    ["rest-spread", "How do rest and spread syntax differ?", "Spread expands values out of an iterable or object into another structure, while rest collects multiple remaining values into one variable. The syntax looks similar, but the direction of data flow is opposite.", "Call out expand versus collect."],
    ["destructuring", "Why is destructuring useful?", "Destructuring makes code more readable by extracting only the values you need from arrays or objects. It also reduces repetitive access patterns and can make function parameters clearer when used carefully.", "Mention readability rather than calling it only shorthand."],
    ["modules-commonjs-esm", "What is the difference between CommonJS and ES modules?", "CommonJS uses require and module.exports and is historically common in Node.js, while ES modules use import and export and align with the JavaScript language standard. The syntax, loading behavior, and tooling support differ enough that teams should be explicit about which module system they use.", "Use require versus import as the simple anchor."],
    ["memory-leaks-js", "How can memory leaks happen in JavaScript applications?", "Memory leaks often happen when references are kept alive unintentionally through closures, global state, event listeners, or caches that are never cleaned up. Leaks are really about object reachability, not only about allocation.", "Reachability is the core concept."],
    ["null-vs-undefined", "What is the difference between null and undefined?", "Undefined usually means a value has not been assigned, while null is typically used intentionally to represent an empty or absent value. The distinction matters because one often reflects default runtime state and the other reflects program intent.", "Intentional absence is a good phrase for null."],
    ["error-handling-js", "How do you handle errors in asynchronous JavaScript code?", "I keep the error path explicit with try and catch around await-based code or catch handlers around promise chains, and I avoid swallowing errors silently. Good async error handling makes failures observable and keeps cleanup behavior predictable.", "Visibility of failures matters as much as catching them."],
    ["set-map-usage", "When would you use Set or Map instead of arrays or plain objects?", "I use Set when uniqueness matters and Map when key lookups are central and keys may not be plain strings. They express intent better than forcing arrays or objects to simulate behaviors they were not designed for.", "Explain the problem the structure solves."],
    ["immutability-js", "Why is immutability useful in JavaScript applications?", "Immutability makes state changes easier to reason about because old values are not being modified in place unexpectedly. This reduces side effects, improves debugging, and fits well with UI patterns that depend on detecting changes by reference.", "Tie it to predictability and change detection."],
    ["strict-mode", "What does strict mode change in JavaScript?", "Strict mode removes some error-prone behavior by turning silent problems into explicit errors and tightening parts of the language semantics. It helps catch mistakes earlier and makes code behavior more deliberate.", "Early error detection is the main value."],
    ["microtasks-macrotasks", "What is the difference between microtasks and macrotasks?", "Microtasks such as promise callbacks run before the event loop moves on to the next macrotask, while macrotasks include items like timers and I O callbacks. Understanding the order matters when debugging execution timing and UI responsiveness.", "Execution order is what interviewers usually care about."],
    ["optional-chaining", "When is optional chaining useful?", "Optional chaining is useful when accessing nested properties that may not exist and you want to stop safely instead of throwing. It improves readability when the missing path is expected and should simply produce undefined.", "Use it for expected absence, not as a substitute for good design."],
    ["functional-vs-imperative-js", "How do functional and imperative JavaScript styles differ?", "Imperative code focuses on step-by-step state changes, while functional style emphasizes transforming inputs into outputs with fewer side effects. Both are useful, and strong JavaScript code usually chooses the clearer style for the specific problem.", "Do not frame one style as always superior."],
    ["json-serialize-limits", "What are some limits of JSON serialization in JavaScript?", "JSON does not preserve functions, undefined values, special object types like Map cleanly, or circular references without extra handling. It is great for simple data interchange, but it is not a full fidelity representation of arbitrary runtime state.", "Mention circular references and type loss."],
    ["promise-all-vs-allsettled", "When would you use Promise.all versus Promise.allSettled?", "I use Promise.all when all tasks must succeed together and I want fast failure, while Promise.allSettled is better when I need the outcome of every task even if some fail. The right choice depends on whether partial results are still useful.", "Explain fast failure versus complete results."],
    ["generators-js", "What problem do generators solve in JavaScript?", "Generators let a function pause and resume, which is useful for representing sequences, lazy iteration, or custom control flow. They are most helpful when producing values over time is clearer than building everything eagerly.", "Use lazy iteration as the concrete example."]
  ],
  "react": [
    ["react-lifecycle-hooks", "How do lifecycle concepts map to hooks in React?", "Hooks such as useEffect cover patterns that used to be handled across lifecycle methods, but the mindset is different because effects should describe synchronization with external systems rather than mirror old class APIs directly. Thinking in effects and dependencies is more important than memorizing class method mapping.", "Do not reduce hooks to a class-component translation table."],
    ["server-vs-client-state", "What is the difference between server state and client state in React apps?", "Client state usually controls UI-specific behavior such as open panels or local form input, while server state represents data fetched from external systems and has to deal with loading, freshness, and synchronization. Mixing them carelessly often creates unnecessary complexity.", "Freshness and synchronization are the key distinctions."],
    ["react-composition", "Why is composition important in React?", "Composition lets small components build larger behavior without hardcoding too much into one place. It improves reuse and maintainability because behavior can be assembled from clear pieces rather than repeated or tightly coupled logic.", "Mention reuse through structure, not inheritance."],
    ["react-error-boundaries", "What problem do error boundaries solve?", "Error boundaries stop rendering errors in one part of the tree from crashing the whole interface and allow a fallback UI to appear instead. They improve resilience, but they do not replace good error handling in events or async code.", "Be clear about what they do not catch."],
    ["state-management-choice", "How do you decide whether local state is enough or a shared state solution is needed?", "I first look at who actually needs the data and how often it changes. If the state stays close to one area of the UI, local state is usually simpler. Shared solutions help when many distant parts of the app truly need the same source of truth.", "Prefer the simplest scope that works."],
    ["react-routing", "What should routing do well in a React application?", "Routing should make navigation predictable, keep URLs meaningful, and preserve the ability to deep-link important screens. Good routing supports both user navigation and product structure without turning every state change into a route.", "Meaningful URLs matter for both UX and SEO."],
    ["memoization-react", "When is memoization useful in React?", "Memoization is useful when profiling shows repeated work or rerenders are actually expensive enough to matter. Used too early, it adds complexity without improving the real user experience.", "Lead with measurement before optimization."],
    ["custom-hooks", "What makes a custom hook well-designed?", "A good custom hook groups one coherent piece of reusable stateful behavior behind a simple interface. It should hide repetition, expose clear inputs and outputs, and avoid becoming a dumping ground for unrelated logic.", "Coherence matters more than clever abstraction."],
    ["react-accessibility", "What accessibility concerns matter in React apps?", "The same accessibility concerns matter as in any web UI, including semantic structure, keyboard interaction, focus management, and clear labels. React does not remove those responsibilities, so component design should support accessible behavior by default.", "Do not treat accessibility as only ARIA attributes."],
    ["hydration-meaning", "What is hydration in React?", "Hydration is the process where React attaches interactive behavior to HTML that was already rendered on the server. It allows faster initial content display while still enabling a dynamic client-side experience.", "Explain the server-rendered HTML part clearly."],
    ["rendering-bugs", "How do you debug unexpected rerenders in React?", "I start by identifying which component rerenders, what state or props changed, and whether the rerender is actually harmful. Then I trace the source of change rather than adding memoization blindly.", "Not every rerender is a bug."],
    ["forms-controlled-uncontrolled", "When would you choose controlled versus uncontrolled form inputs?", "Controlled inputs are better when validation, formatting, or immediate UI reaction matters, while uncontrolled inputs can be simpler when you only need values at submission time. The choice should match how much React truly needs to manage the field.", "Match the control level to the product need."],
    ["react-testing", "What should you test in a React component?", "I test the user-visible behavior, important state transitions, and the interactions that matter most, rather than focusing only on internal implementation details. Good tests give confidence during change instead of locking the component to one internal structure.", "Behavior over implementation is the stronger testing answer."],
    ["suspense-purpose", "What problem does Suspense try to address?", "Suspense is designed to help coordinate loading boundaries so parts of the interface can wait for async data or code more intentionally. The key idea is controlling loading experience structurally instead of scattering ad hoc spinners everywhere.", "Structure the loading experience, do not just mention fallback text."],
    ["react-reconciliation", "What is reconciliation in React?", "Reconciliation is how React compares the previous and next element trees to decide what UI changes are needed. Keys, component identity, and tree shape all affect how efficiently and correctly this process works.", "Connect reconciliation to UI updates and keys."],
    ["co-locating-state", "Why is colocating state often a good idea?", "Keeping state close to where it is used reduces unnecessary coupling and makes components easier to understand. State should move upward only when multiple parts of the UI truly need to coordinate around it.", "Local clarity is usually the better default."],
    ["react-bundle-size", "How do you keep a React app from becoming unnecessarily heavy?", "I keep dependencies intentional, load code lazily where that helps, and avoid shipping large abstractions for small problems. Frontend performance is partly about runtime work and partly about the amount of code the user has to download.", "Bundle size and runtime both matter."]
  ],
  "nodejs": [
    ["node-process-model", "How does Node.js handle many connections efficiently?", "Node.js uses an event-driven model with non-blocking I O, allowing one process to manage many waiting operations without dedicating a thread to each request. The efficiency comes from not wasting the main thread on idle waiting.", "Anchor the explanation on non-blocking I O."],
    ["cluster-workers", "When would you use clustering or multiple Node.js processes?", "I use multiple processes when I need to take advantage of multiple CPU cores or isolate workloads better than one event loop can handle. Node.js scales well horizontally, but each process still needs good observability and safe state design.", "Mention CPU cores and isolation."],
    ["background-jobs", "When should work move out of the request cycle into background jobs?", "I move work out of the request cycle when it is slow, retryable, or not required before the user gets an immediate response. Queues help protect latency-sensitive endpoints from tasks that would otherwise block user-facing performance.", "Protecting the request path is the key idea."],
    ["connection-pooling", "Why is connection pooling important in backend services?", "Connection pooling avoids the cost of creating fresh connections repeatedly and helps manage limited backend resources more predictably. It becomes especially important under load when connection overhead can become a bottleneck of its own.", "Tie it to load behavior."],
    ["graceful-shutdown", "What is graceful shutdown in a Node.js service?", "Graceful shutdown means the process stops accepting new work, finishes or safely aborts in-flight work, and closes resources cleanly before exiting. This reduces dropped requests and inconsistent state during deployments or failures.", "Emphasize in-flight work and cleanup."],
    ["rate-limiting", "Why would you add rate limiting to an API?", "Rate limiting protects the system from abuse, accidental overload, and unfair resource usage. It also helps keep service quality more predictable for normal users during spikes or malicious traffic.", "Fairness and protection are the main reasons."],
    ["node-caching", "How do you decide what to cache in a backend service?", "I cache data that is expensive to compute or fetch repeatedly and where a bounded amount of staleness is acceptable. The value of caching depends on access patterns, invalidation strategy, and whether it actually protects the hot path.", "Never talk about caching without invalidation tradeoffs."],
    ["websockets-vs-http", "When would WebSockets be a better fit than plain HTTP?", "WebSockets are useful when the server needs to push updates continuously or latency between many small interactions matters more than request-response simplicity. Plain HTTP is still better when the communication is mostly independent requests.", "Show that WebSockets are not automatically better."],
    ["node-security-basics", "What backend security basics matter in a Node.js API?", "Input validation, authentication, authorization, secrets management, dependency hygiene, and careful error exposure all matter. Security is strongest when those practices are part of everyday development, not only audit time.", "Authorization is not the same as authentication."],
    ["logging-strategy", "What makes application logging useful?", "Useful logging helps reconstruct behavior, correlate requests, and understand failures without flooding the system with noise. The best logs are structured, consistent, and focused on events that help operators make decisions.", "Mention signal versus noise."],
    ["database-transactions", "When are database transactions important?", "Transactions are important when multiple related operations must either succeed together or fail together to preserve consistency. They are most useful when the data model would become invalid or misleading if only part of the work completed.", "Preserving consistency is the heart of the answer."],
    ["api-idempotency", "Why is idempotency useful in APIs?", "Idempotency lets clients retry requests safely without causing duplicate side effects, which is especially important when networks are unreliable or operations are costly. It makes systems more resilient under real-world failure conditions.", "Retries are the main motivation."],
    ["queue-visibility", "What metrics matter for background job queues?", "Queue depth, processing latency, retry rate, failure rate, and age of oldest job are all useful because they show both current health and whether work is falling behind. Queue metrics matter because backlog growth often signals user impact before support tickets do.", "Mention backlog growth explicitly."],
    ["service-healthchecks", "What should a health check endpoint really indicate?", "A good health check should reflect whether the service can do the work it claims to handle, not just whether the process is running. Sometimes that means checking critical dependencies, and sometimes it means a lightweight readiness distinction instead of one generic status.", "Differentiate liveness from readiness if helpful."],
    ["schema-validation", "Why validate request payloads at the boundary?", "Validation at the boundary prevents invalid data from spreading through the system and makes API behavior more predictable for clients. It also simplifies downstream logic because handlers can assume the input shape is already trustworthy.", "Boundary validation reduces internal complexity."],
    ["node-memory-usage", "How do you investigate rising memory usage in a Node.js service?", "I would compare memory patterns over time, inspect whether objects are being retained unexpectedly, and relate spikes to traffic or specific code paths. Memory problems become easier to fix when the retention source is identified rather than guessed.", "Retention is a stronger concept than just saying leak."],
    ["circuit-breakers", "What problem do circuit breakers solve in distributed systems?", "Circuit breakers help stop repeated calls to an unhealthy dependency from causing cascading failures and wasted resources. They improve resilience by letting the system fail more deliberately instead of collapsing under repeated timeouts.", "Cascading failure is the main phrase here."]
  ],
  "coding-interview": [
    ["hash-map-choice", "Why are hash maps so common in coding interviews?", "Hash maps give fast average-case lookups and make it easier to track frequency, membership, and complements without repeated scanning. Many interview problems become simpler once you recognize that fast lookup is the missing ingredient.", "Fast lookup is often the key optimization."],
    ["sliding-window", "When is the sliding window pattern useful?", "Sliding window is useful when the problem involves contiguous ranges and you need to maintain information as the range expands or contracts. It often replaces repeated nested scans with a more efficient rolling calculation.", "Contiguous ranges are the main clue."],
    ["prefix-sum", "What does a prefix sum help with?", "A prefix sum lets you compute range totals quickly by precomputing cumulative values once and reusing them. It is especially helpful when many subarray sum queries would otherwise repeat the same work.", "Mention repeated range calculations."],
    ["heap-use-case", "When would you use a heap in a coding problem?", "A heap is useful when you repeatedly need the smallest or largest element while the collection changes over time. It helps with top-k problems, scheduling, and streaming comparisons where full sorting is unnecessary.", "Top-k is the simplest example."],
    ["greedy-approach", "How do you know whether a greedy algorithm is safe?", "A greedy approach is safe only when the local best choice can be shown to lead to a globally correct solution. If that proof is missing, the fast-looking approach may just be a guess.", "Say proof or justification explicitly."],
    ["backtracking", "When should you think of backtracking?", "Backtracking is a good fit when you need to explore combinations, permutations, or constrained decision trees where partial choices can be invalidated and undone systematically. The pattern works best when pruning can reduce the search space meaningfully.", "Use combinations and constraints as the clues."],
    ["union-find", "What kinds of problems is union find good for?", "Union find is useful for connectivity questions where elements need to be grouped dynamically, such as checking whether nodes belong to the same component. It is especially powerful when repeated merges and connectivity checks appear together.", "Connectivity is the core signal."],
    ["topological-sort", "When do you use topological sort?", "I use topological sort when dependencies form a directed acyclic graph and I need an order that respects those dependencies. Build systems, prerequisite scheduling, and dependency resolution are classic examples.", "Directed acyclic graph is the important phrase."],
    ["recurrence-relation", "How do you build confidence in a dynamic programming recurrence?", "I define the state carefully, explain what smaller result it depends on, and test the recurrence on very small examples before trusting it broadly. Confidence comes from understanding what the state means, not from memorizing formulas.", "State meaning comes before implementation."],
    ["binary-search-answer-space", "What is binary search on the answer?", "It is a technique where you binary search over possible answer values instead of positions in a sorted array, as long as you can test whether a candidate answer is feasible. It works when feasibility changes in a monotonic way across the search space.", "Monotonic feasibility is the clue."],
    ["graph-vs-tree", "How do graph problems differ from tree problems in interviews?", "Trees usually give you stronger structure such as one path between nodes and no cycles, while graph problems require more explicit handling of cycles, visited tracking, and possibly disconnected components. That extra flexibility is what makes graph logic broader and sometimes trickier.", "Cycles and disconnected components are the differentiators."],
    ["invariants-coding", "Why are invariants useful while coding?", "An invariant gives you a property that should remain true throughout the algorithm, which makes correctness easier to reason about and bugs easier to detect. Strong candidates use invariants to explain why the approach works, not only how it runs.", "Invariants help both correctness and communication."],
    ["complexity-communication", "How should you communicate time and space complexity in an interview?", "I state complexity after explaining the approach and tie it to the dominant operations in the algorithm rather than reciting symbols mechanically. Good communication shows where the cost comes from and whether the tradeoff is justified.", "Explain the source of the complexity."],
    ["edge-case-strategy", "How do you systematically test edge cases while coding?", "I check empty input, smallest valid input, duplicates, boundaries, sorted or reverse-sorted patterns if relevant, and any values that change branch behavior. Systematic edge-case thinking prevents many avoidable interview mistakes.", "Show a repeatable testing habit."],
    ["recursion-stack", "What risk comes with recursive solutions?", "Recursive solutions can be elegant, but deep recursion can cause stack overflow or unnecessary overhead if the input size grows beyond safe limits. I keep that tradeoff in mind when choosing between recursion and iteration.", "Elegance does not remove stack risk."],
    ["top-k-approaches", "How do you choose between sorting and a heap for top-k problems?", "Sorting the whole set can be simpler, but a heap is better when k is much smaller than n and you do not need full order. The right choice depends on the relative sizes and whether the data arrives all at once or as a stream.", "Tie the choice to n, k, and input style."],
    ["interview-narration", "Why does narration matter during a coding interview?", "Narration keeps the interviewer aligned with my assumptions, lets them correct misunderstandings early, and makes my reasoning visible even before the code is finished. Strong narration reduces the chance that correct thinking gets mistaken for silence or confusion.", "Visibility of reasoning matters."]
  ],
  "behavioral": [
    ["dealt-with-ambiguity", "Tell me about a time you worked through ambiguity.", "I explain how I identified what had to be known immediately, what could remain uncertain, and how I moved the work forward with explicit assumptions. Ambiguity handling is strongest when it produces clarity for the whole team rather than just personal comfort.", "Show how you created clarity for others."],
    ["disagreed-decision", "Tell me about a time you disagreed with a decision.", "I focus on how I raised the concern respectfully, used evidence instead of ego, and then supported the final decision once it was made unless the risk was serious enough to escalate further. The point is to show judgment and professionalism together.", "Respectful dissent is the theme."],
    ["went-beyond-role", "Describe a time you went beyond your formal role.", "I choose an example where I saw a gap that was hurting delivery or quality and took responsibility for closing it even though it was not assigned to me directly. Good answers show initiative that helped the team, not a need for personal credit.", "Initiative should connect to team outcome."],
    ["difficult-stakeholder", "How do you work with a difficult stakeholder?", "I try to understand what pressure they are under, what outcome they care about, and where communication is breaking down. Most difficult stakeholder situations improve when assumptions are clarified and tradeoffs are made explicit instead of personal.", "Depersonalize the conflict."],
    ["missed-deadline", "Tell me about a time you missed a deadline.", "I explain why the deadline was missed without hiding my role in it, what signals were missed earlier, and how I improved estimation or communication afterward. The strongest version shows responsibility and prevention rather than excuses.", "Take responsibility and show improvement."],
    ["building-trust", "How do you build trust with a new team?", "I build trust through reliability, clarity, and responsiveness rather than trying to impress people quickly. Delivering on commitments and communicating early when risks appear usually matters more than big promises.", "Reliability is the core idea."],
    ["hard-priority-call", "Tell me about a time you had to make a hard priority decision.", "I describe the competing needs, the criteria I used to choose, and how I communicated the tradeoff so the decision was understandable even for people who preferred a different outcome. Priority decisions are strongest when they are explainable.", "Explain the criteria, not only the result."],
    ["learned-quickly", "Describe a time you had to learn something quickly.", "I explain how I reduced the learning problem into the minimum knowledge needed to make progress, then validated that understanding in practice instead of studying indefinitely. Fast learning in engineering is usually about focus more than speed alone.", "Focus matters more than volume."],
    ["team-under-stress", "How do you help a team under stress avoid bad decisions?", "I slow the discussion just enough to make priorities, owners, and constraints explicit. Stress creates mistakes when teams start acting on assumptions, so structure and calm communication often prevent bigger damage.", "Create structure under pressure."],
    ["persuasion-example", "Tell me about a time you persuaded others to change direction.", "I focus on how I framed the issue with evidence, acknowledged counterarguments fairly, and proposed a path that reduced risk rather than only arguing harder. Good persuasion in teams feels collaborative, not manipulative.", "Evidence and fair framing matter."],
    ["working-across-functions", "How do you work across functions like product, design, and engineering?", "I make assumptions visible, ask what each function is optimizing for, and translate technical implications into practical tradeoffs. Cross-functional work improves when everyone can see how their decisions affect the others.", "Translation across perspectives is the skill."],
    ["ownership-example", "Tell me about a time you showed ownership.", "I choose an example where I carried a problem from unclear status to useful resolution by coordinating people, closing gaps, and verifying the outcome instead of stopping at implementation. Ownership is follow-through under uncertainty.", "Follow-through is the strongest ownership signal."],
    ["de-escalated-conflict", "Describe a time you de-escalated tension in a team.", "I explain how I separated the real issue from the emotion around it and helped the group return to shared goals and facts. De-escalation is less about being passive and more about restoring useful problem solving.", "Shared goals help reset tense conversations."],
    ["feedback-to-others", "How do you give constructive feedback to others?", "I focus on specific behavior, its impact, and what better execution would look like instead of making the feedback personal or vague. Constructive feedback should help someone improve without leaving them defensive or confused.", "Specific behavior is easier to act on."],
    ["motivation-example", "What kind of work motivates you most?", "I am usually most motivated by meaningful problems, clear ownership, and environments where strong execution actually improves the outcome. The answer works best when the motivation aligns naturally with the role rather than sounding generic.", "Align motivation with the role."],
    ["adapted-change", "Tell me about a time you had to adapt quickly to change.", "I explain what changed, what remained important, and how I adjusted my plan without losing the core objective. Adaptability is strongest when it looks controlled and thoughtful rather than reactive.", "Show controlled adjustment, not chaos."],
    ["handled-unclear-feedback", "What do you do when feedback is vague or unclear?", "I ask clarifying questions until the expected behavior is concrete enough to act on. Vague feedback only becomes useful when translated into observable changes or decisions.", "Turn vagueness into specifics."]
  ],
  "hr": [
    ["career-goals", "What are your long-term career goals?", "I connect my long-term growth to increasing responsibility, depth, and impact while still showing that I am focused on doing this role well first. Long-term answers work best when they are ambitious but realistic.", "Stay ambitious without sounding detached from the role."],
    ["company-research", "What do you know about our company?", "I focus on the company product, customers, market position, or culture in a specific way that shows I prepared intentionally. A strong answer proves real interest rather than repeating one generic sentence from the homepage.", "Specific preparation matters."],
    ["handle-rejection", "How do you handle rejection or setbacks in your career?", "I treat setbacks as information about what needs to improve rather than as a signal to become defensive. The strongest answer shows reflection, recovery, and a concrete change in later behavior.", "Recovery and learning are the key themes."],
    ["ideal-manager", "What kind of manager helps you do your best work?", "I usually do best with managers who create clarity, give useful feedback, and trust people to execute with ownership. The point is not to sound demanding, but to describe the conditions where you perform most effectively.", "Keep it professional and balanced."],
    ["work-environment", "What kind of work environment do you prefer?", "I prefer an environment with clear expectations, thoughtful collaboration, and enough autonomy to own outcomes fully. The answer is strongest when it reflects how you actually work rather than what you think sounds good.", "Authenticity matters here."],
    ["biggest-achievement", "What is your biggest professional achievement?", "I choose an achievement that shows the kind of value most relevant to the role, explain the context and challenge, and make my contribution and outcome clear. The answer should show impact, not just activity.", "Use a measurable outcome if possible."],
    ["gap-in-resume", "How do you explain a gap in your resume?", "I explain it directly and calmly, then focus on what I learned, improved, or handled during that period. A clear and honest explanation usually lands better than trying to over-defend the gap.", "Directness is better than overexplaining."],
    ["team-or-individual", "Do you prefer working alone or in a team?", "I am comfortable with both, but the real answer depends on the problem. Deep individual work is valuable for focused execution, while teamwork is essential when alignment, feedback, and shared ownership matter.", "Do not force a false either-or answer."],
    ["pressure-hr", "How do you deal with workplace pressure?", "I deal with pressure best when I clarify what matters most, reduce avoidable uncertainty, and work from concrete next steps instead of reacting emotionally. The goal is not to pretend pressure does not exist, but to stay effective within it.", "Effectiveness under pressure is stronger than generic calmness."],
    ["learning-plan", "How do you keep your skills current?", "I update my skills by combining deliberate learning with practical application so new knowledge turns into usable judgment. I usually learn best when I connect reading or courses to real projects or experiments.", "Practical application matters more than consuming content."],
    ["why-role-change", "Why are you changing roles or industries?", "I frame the change around stronger fit, stronger motivation, and transferable skills rather than dissatisfaction alone. The best answer makes the move sound intentional and credible.", "Make the move sound deliberate."],
    ["remote-work", "How do you work effectively in remote or hybrid settings?", "I work well remotely when expectations, communication rhythms, and ownership are clear. Good remote work depends on written clarity and timely communication more than constant meetings.", "Written clarity is a useful point."],
    ["managing-multiple-offers", "What would you do if you had multiple offers?", "I would compare role fit, growth, team quality, and long-term value rather than choosing only by the first visible number. Recruiters usually want to see that my decision process is thoughtful and professional.", "Decision quality matters more than sounding clever."],
    ["deal-breakers", "What factors matter most to you when choosing a job?", "I care most about the quality of the role, the kind of problems I will solve, the team environment, and whether I can grow while creating real value. Compensation matters, but strong fit is broader than compensation alone.", "Keep the answer balanced."],
    ["availability-start", "When can you start contributing meaningfully after joining?", "I would expect to start contributing in a limited but real way quickly by learning the product, team, and systems deliberately, then ramp up as I understand the domain. This answer works best when it shows urgency without pretending onboarding is unnecessary.", "Show realistic ramp-up."],
    ["why-now", "Why is now the right time for you to make a move?", "I explain why my current experience, goals, and the opportunity in front of me now line up better than they did earlier. The answer should sound like a thoughtful career move, not restlessness.", "Make timing sound intentional."],
    ["team-culture", "What kind of team culture helps you do your best work?", "I work best in cultures that value clarity, accountability, and constructive feedback because those qualities make it easier to improve quickly and collaborate well. The answer should reflect how you actually succeed on teams.", "Use real qualities, not buzzwords alone."]
  ]
};

const companyQuestionPool = [
  ["company-culture-fit", "What kind of culture helps you perform your best work at {company}?", "I do best in cultures that combine high standards with clear ownership and respectful collaboration. In a company like {company}, strong culture should make decision quality and execution stronger, not just sound good in recruiting materials.", "Tie culture to how work gets done."],
  ["company-role-alignment", "Why do you think you are a fit for {company}?", "I would connect my strengths to the kind of problems {company} appears to solve and the expectations of the role. The strongest fit answer is specific about what I can contribute instead of only saying I admire the brand.", "Specific contribution is stronger than admiration."],
  ["company-prioritization", "How do you prioritize work when everything seems urgent?", "I separate urgency from impact, identify dependencies, and align with stakeholders on what really moves the outcome forward. In fast-moving environments like {company}, disciplined prioritization is more valuable than reacting to every request equally.", "Impact matters more than noise."],
  ["company-customer-thinking", "How do you think about customer impact in your engineering decisions?", "I ask how the decision affects reliability, speed, clarity, and long-term trust from the user perspective. Strong engineering at {company} should connect technical choices to the actual experience of the customer.", "Translate engineering into user impact."],
  ["company-debugging-process", "Describe your debugging process for a complex issue.", "I narrow the problem by reproducing it, identifying where reality diverges from expectation, and validating one hypothesis at a time. The point is to make the issue smaller and more observable instead of jumping between guesses.", "Reduce the problem before trying random fixes."],
  ["company-delivery-balance", "How do you balance delivery speed with quality?", "I try to protect quality on the highest-risk paths while reducing scope where needed to keep momentum. Good engineering at {company} should show judgment about where speed helps and where cutting corners creates expensive problems later.", "Scope can shrink before quality does."],
  ["company-learning", "How do you ramp up quickly in a new domain?", "I identify the concepts that block useful progress, learn enough to make a first contribution, and then deepen understanding through real work. Fast ramp-up is usually about learning the right things in the right order.", "Sequence matters more than volume."],
  ["company-collaboration", "How do you work with cross-functional teams?", "I make tradeoffs visible, ask what each function is optimizing for, and keep communication concrete enough for decisions to move. Cross-functional work succeeds when people can reason about the same problem from different perspectives.", "Make tradeoffs visible."],
  ["company-feedback", "How do you handle feedback that you disagree with at first?", "I try to understand the reasoning before reacting, then I evaluate whether the concern reveals a gap in my assumptions or communication. Even when I disagree, I want the discussion to improve the outcome instead of becoming personal.", "Understanding comes before defending."],
  ["company-system-thinking", "How do you think about designing systems that stay reliable at scale?", "I focus on clear boundaries, observability, graceful failure behavior, and realistic operational tradeoffs. Reliability at {company} should be designed into the system and the rollout process, not added after incidents happen.", "Reliability includes operations, not just architecture."],
  ["company-ambiguity", "How do you operate when the next step is not clearly defined?", "I turn ambiguity into specific questions, define the decision that matters most, and propose a path instead of waiting passively. Strong performers in companies like {company} reduce uncertainty for the team rather than only managing their own discomfort.", "Reduce uncertainty for the team."],
  ["company-metrics", "What metrics would you watch after launching a feature?", "I would watch the metrics most closely tied to user success and system health, such as adoption, error rate, latency, and any feature-specific business signal that should move. Metrics only help if they reflect real product behavior.", "Use both user and system signals."],
  ["company-ownership", "What does ownership mean to you in a company like {company}?", "Ownership means carrying a problem through ambiguity, implementation, validation, communication, and follow-up until the outcome is reliable. It is not just about writing code quickly; it is about making sure the result actually holds up.", "Ownership includes follow-through."],
  ["company-tradeoffs", "How do you explain tradeoffs when there is no perfect solution?", "I compare the options in terms of what each one optimizes, what risk it introduces, and why one is the best fit for the real constraints. Good tradeoff communication helps teams make decisions they can defend later.", "Explain what each option optimizes for."],
  ["company-testing", "How do you decide what to test before release?", "I prioritize tests around the highest-risk behavior, critical integrations, and the paths most likely to hurt users if they fail. A good testing approach is driven by risk and consequence, not by trying to test everything equally.", "Risk-driven testing is a stronger answer."],
  ["company-prior-experience", "How would your previous experience help you at {company}?", "I would connect my past work to the challenges this role likely faces, whether that is product quality, system reliability, debugging depth, or cross-team execution. The value of experience is strongest when it transfers directly to the next environment.", "Transferable value matters more than title names."],
  ["company-incident-learning", "What should a team learn after an incident?", "A strong team should learn what assumptions failed, what safeguards were missing, and what changes will reduce repeat risk. The point is not to produce blame-heavy documentation, but to improve how the system and the team behave next time.", "Prevention is the goal of learning."]
];

for (const category of all) {
  const existingSlugs = new Set((category.questions || []).map((item) => item.slug));
  const additions = category.kind === "company"
    ? companyQuestionPool.map(([key, question, answer, tip]) => ({
        slug: `${category.companyName ? slugify(category.companyName) : slugify(category.title)}-${key}`,
        question: question.replaceAll("{company}", category.companyName || category.title),
        answer: answer.replaceAll("{company}", category.companyName || category.title),
        tip
      }))
    : (topicQuestionPools[category.slug] || []).map(([slug, question, answer, tip]) => ({ slug, question, answer, tip }));

  for (const item of additions) {
    if ((category.questions || []).length >= TARGET) break;
    if (existingSlugs.has(item.slug)) continue;
    category.questions.push(item);
    existingSlugs.add(item.slug);
  }
}

fs.writeFileSync(postsPath, JSON.stringify(posts, null, 2) + "\n");
fs.writeFileSync(researchedPath, JSON.stringify(researched, null, 2) + "\n");

const combined = [...posts, ...researched];
console.log(JSON.stringify({
  categories: combined.length,
  totalQuestions: combined.reduce((sum, category) => sum + category.questions.length, 0),
  minQuestions: Math.min(...combined.map((category) => category.questions.length)),
  maxQuestions: Math.max(...combined.map((category) => category.questions.length))
}, null, 2));
